version: 2.1
workflows:
  androidtest:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

jobs:
  test:
    docker:
      - image: circleci/android:api-28-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Build debug APK and release APK
          command: |
            echo "$PIXLEE_PROPERTIES" | base64 --decode > pixleekey.properties
            ls -al
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project pixlee-sdk
      - run:
          name: Test with Firebase Test Lab
          command: >
            sudo gcloud firebase test android run \
              --type instrumentation \
              --app app/build/outputs/apk/debug/app-debug.apk \
              --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --device model=Nexus6,version=21,locale=en,orientation=portrait \
              --results-bucket cloud-test-pixlee-sdk
