version: 2.1
executors:
  default:
    docker:
      - image: cimg/base:2020.01
workflows:
  testing:
    jobs:
      - unit:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - ui:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - refresh-documentation:
          requires:
            - unit
            - ui
          filters:
            branches:
              only: master
jobs:
  unit:
    docker:
      - image: circleci/android:api-28-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - copy-pixlee-credentials
      - unit-tests
  ui:
    docker:
      - image: circleci/android:api-28-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - copy-pixlee-credentials
      - ui-tests
  refresh-documentation:
    executor: default
    steps:
      - deploy:
          name: Refresh eng-docs
          command: |
            curl --user ${CIRCLECI_TOKEN}: \
              --data 'build_parameters[CIRCLE_JOB]=build-deploy' \
              https://circleci.com/api/v1.1/project/github/pixlee/eng-docs/tree/master
commands:
  copy-pixlee-credentials:
    steps:
      - run:
          name: Store Pixlee crecentials into pixleekey.properties
          command: |
            echo "$PIXLEE_PROPERTIES" | base64 --decode > pixleekey.properties
            ls -al
  unit-tests:
    steps:
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
  ui-tests:
    steps:
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project pixlee-sdk
      - run:
          name: Test with Firebase Test Lab
          command: >
            sudo gcloud firebase test android run \
              --type instrumentation \
              --app app/build/outputs/apk/debug/app-debug.apk \
              --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --device model=Nexus6,version=21,locale=en,orientation=portrait \
              --results-bucket cloud-test-pixlee-sdk